site_name: tmap
pages: 
- tmap: index.md
- User guide: 
    - Basic Usage: basic.md
    - Parameter Selection: param.md
    - Visulization: vis.md
    - Association: association.md
    - How TMAP work: how2work.md
    - Demonstrate a few examples: example.md
    - API Reference: api.md
    - Reference: reference.md
- About:
    - License: 1.md
    - Release Notes: 2.md
- FAQ: FAQ.md
theme: readthedocs

repo_url: https://github.com/444thLiao/tmap

